package me.sivieri.aoc2023.day11

import org.hamcrest.MatcherAssert.assertThat
import org.hamcrest.Matchers.`is`
import org.junit.Test

class ObservatoryTest {

    @Test
    fun `part 1 example`() {
        val input = """
            ...#......
            .......#..
            #.........
            ..........
            ......#...
            .#........
            .........#
            ..........
            .......#..
            #...#.....
        """.trimIndent()
        val observatory = Observatory(input, weight = 2)
        val result = observatory.sumShortestPaths()
        assertThat(result, `is`(374))
    }

    @Test
    fun `part 2 example 10`() {
        val input = """
            ...#......
            .......#..
            #.........
            ..........
            ......#...
            .#........
            .........#
            ..........
            .......#..
            #...#.....
        """.trimIndent()
        val observatory = Observatory(input, weight = 10)
        val result = observatory.sumShortestPaths()
        assertThat(result, `is`(1030))
    }

    @Test
    fun `part 2 example 100`() {
        val input = """
            ...#......
            .......#..
            #.........
            ..........
            ......#...
            .#........
            .........#
            ..........
            .......#..
            #...#.....
        """.trimIndent()
        val observatory = Observatory(input, weight = 100)
        val result = observatory.sumShortestPaths()
        assertThat(result, `is`(8410))
    }

}